# Generated by Django 4.0.2 on 2022-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [

        migrations.AlterModelTable(
            name="profile",
            table="user_profiles",
        ),
    ]
