# Generated by Django 4.0.2 on 2022-03-14 18:01

import datetime
from django.db import migrations, models
import petstagram.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pet_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PetPhoto',
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[petstagram.main.validators.MinDateValidator(datetime.date(1920, 1, 1))]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True),
        ),
    ]
